hotpulse/web_app/app.py
import os

from flask import Flask

from config.environment import Environment
from web_app.blueprints import api

app = Flask(__name__)


def create_app() -> Flask:  # noqa
    os.environ["APP_ENVIRONMENT"] = "development"
    Environment.bootstrap()
    app.register_blueprint(api.bp)
    return app

hotpulse/web_app/blueprints/api.py
import uuid
from datetime import datetime

from flask import Blueprint, Response, jsonify, render_template, request

from exceptions.queue_connection_error import QueueConnectionError
from models.task import Priority, Status, Task
from services.enqueue_task import enqueue_task
from services.get_all_hotel_tasks import get_all

bp = Blueprint("api", __name__)


def get_priority(priority: str) -> Priority:
    match priority.lower():
        case "low":
            return Priority.LOW
        case "medium":
            return Priority.MEDIUM
        case "high":
            return Priority.HIGH
        case _:
            raise ValueError("Invalid priority")


@bp.route("/api", methods=["GET", "POST"])
def api() -> str | tuple[Response, int]:  # noqa
    if request.method == "POST":
        try:
            task = Task(
                description=request.form.get("description", default=""),
                status=Status.TODO,
                priority=get_priority(request.form.get("priority", default="")),
                created_at=datetime.now(),
            )
            enqueue_task(task)
        except ValueError as e:
            return jsonify(message=f"{e}"), 400
        except QueueConnectionError as e:
            return jsonify(message=str(e)), 503
    return render_template("index.html", tasks=get_all())

hotpulse/web_app/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <title>Hello, world!</title>
  </head>
  <body class="bg-secondary">

    <div class="container">
        <div class="row d-flex justify-content-between align-items-center vh-100 p-5">
            <div class="col-lg-4 bg-light rounded shadow mb-5">
                <form class="p-3" action="{{ url_for('api.api') }}" method="post">
                    <div class="mb-3">
                        <label for="description" class="form-label">Description</label>
                        <input type="text" class="form-control" id="description" name="description" aria-describedby="emailHelp">
                    </div>
                    <div class="mb-3">
                        <label for="priority" class="form-label">Priority</label>
                        <select class="form-select" name="priority" id="priority">
                            <option value="Low">Low</option>
                            <option value="Medium">Medium</option>
                            <option value="High">High</option>
                        </select>
                    </div>
                    <div class="d-grid gap-2 col-6 mx-auto">
                        <button class="btn btn-primary btn-lg my-3" type="submit">Submit</button>
                    </div>
                </form>
            </div>
            <div class="col-lg-6 bg-light h-100 py-3 rounded shadow">
                <div class="container">
                    <div class="row">
                            <h2 class="text-center">Tasks List</h2>
                            <div class="col-12">
                                <table class="table table-responsive table-striped table-hover table-borderless">
                                    <thead class="table-primary text-center">
                                        <tr>
                                            <th scope="col">Descr.</th>
                                            <th scope="col">Priority</th>
                                            <th scope="col">Status</th>
                                            <th scope="col">Created On</th>
                                        </tr>
                                    </thead>
                                    <tbody class="text-center">
                                        {% for task in tasks.values() %}
                                        <tr>
                                        <td>{{task.description}}</td>
                                        <td>{{task.status.name}}</td>
                                        <td>
                                            {% if task.priority.name == "LOW"%}<i class='bx bx-down-arrow-circle text-primary'></i>{% endif %}
                                            {% if task.priority.name == "MEDIUM"%}<i class='bx bx-right-arrow-circle text-success'></i>{% endif %}
                                            {% if task.priority.name == "HIGH"%}<i class='bx bx-up-arrow-circle text-danger'></i>{% endif %}
                                        </td>
                                        <td>{{task.created_at.strftime('%Y-%m-%d %H:%M')}}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>